# Generated by Django 2.0.1 on 2018-01-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
