# Generated by Django 2.0.1 on 2018-01-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180129_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='post',
            name='video_key',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
